##ThymeLeaf配置
spring:
  thymeleaf:
    #prefix：指定模板所在的目录
    prefix: classpath:/templates/
    #check-tempate-location: 检查模板路径是否存在
    check-template-location: true
    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
    suffix:  .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://192.168.232.128:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
####指定读取logback配置文件
#logging:
#  config: classpath:log/logback.xml
###指定log4j.properties配置文件路径
logging:
  config: classpath:log4j.properties


#spring:
#  datasource:
#    ###会员数据库
#    member:
#      jdbc-url: jdbc:mysql://192.168.232.128:3306/user
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.jdbc.Driver
#    ###订单数据库
#    order:
#      jdbc-url: jdbc:mysql://192.168.232.128:3306/order
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.jdbc.Driver

xuan:
  name: xuanran
  age: 25
  address: AnHui